<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MercurePL"
    nsURI="http://MercurePL" nsPrefix="MercurePL">
  <eClassifiers xsi:type="ecore:EClass" name="Engine">
    <eReferences name="mercure" eType="#//Mercure" lowerBound="1" eOpposite="#//Mercure/engine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engine1" eSuperTypes="#//Engine">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engine2" eSuperTypes="#//Engine">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetDriver">
    <eReferences name="mercure" eType="#//Mercure" lowerBound="1" upperBound="-1"
        eOpposite="#//Mercure/netDriver"/>
    <eReferences name="message" eType="#//Message" upperBound="-1" eOpposite="#//Message/netDriver"/>
    <eReferences name="manager" eType="#//Manager" lowerBound="1" upperBound="-1"
        eOpposite="#//Manager/netDriver"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eReferences name="netDriver" eType="ecore:EClass ../MercurePL.ecore#//NetDriver"
        lowerBound="1" eOpposite="#//NetDriver/message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager">
    <eReferences name="mercure" eType="#//Mercure" lowerBound="1" upperBound="-1"
        eOpposite="#//Mercure/manager"/>
    <eReferences name="netDriver" eType="ecore:EClass ../MercurePL.ecore#//NetDriver"
        lowerBound="1" eOpposite="#//NetDriver/manager"/>
    <eReferences name="gUI" eType="#//GUI" lowerBound="1" eOpposite="#//GUI/manager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetDriver1" eSuperTypes="#//NetDriver">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetDriver2" eSuperTypes="#//NetDriver">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager1" eSuperTypes="#//Manager">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager2" eSuperTypes="#//Manager">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GUI">
    <eReferences name="mercure" eType="#//Mercure" lowerBound="1" upperBound="-1"
        eOpposite="#//Mercure/gUI"/>
    <eReferences name="manager" eType="#//Manager" lowerBound="1" upperBound="-1"
        eOpposite="#//Manager/gUI"/>
    <eReferences name="language" eType="ecore:EClass ../MercurePL.ecore#//Language"
        lowerBound="1" eOpposite="#//Language/gUI"/>
    <eReferences name="use" eType="ecore:EClass ../MercurePL.ecore#//Language" lowerBound="1"
        eOpposite="#//Language/UsergUI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GUI1" eSuperTypes="#//GUI">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GUI2" eSuperTypes="#//GUI">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eReferences name="mercure" eType="#//Mercure" lowerBound="1" eOpposite="#//Mercure/language"/>
    <eReferences name="gUI" eType="#//GUI" lowerBound="1" upperBound="-1" eOpposite="#//GUI/language"/>
    <eReferences name="UsergUI" eType="#//GUI" lowerBound="1" eOpposite="#//GUI/use"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageCat1" eSuperTypes="#//Language"/>
  <eClassifiers xsi:type="ecore:EClass" name="Language1_1" eSuperTypes="#//LanguageCat1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Language1_2" eSuperTypes="#//LanguageCat1">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language2_1" eSuperTypes="#//LanguageCat2">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language2_2" eSuperTypes="#//LanguageCat2">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageCat2" eSuperTypes="#//Language">
    <eAnnotations source="optional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mercure">
    <eReferences name="engine" eType="ecore:EClass ../MercurePL.ecore#//Engine" lowerBound="1"
        containment="true" eOpposite="#//Engine/mercure"/>
    <eReferences name="netDriver" eType="ecore:EClass ../MercurePL.ecore#//NetDriver"
        lowerBound="1" containment="true" eOpposite="#//NetDriver/mercure"/>
    <eReferences name="manager" eType="#//Manager" lowerBound="1" containment="true"
        eOpposite="#//Manager/mercure"/>
    <eReferences name="gUI" eType="#//GUI" lowerBound="1" containment="true" eOpposite="#//GUI/mercure"/>
    <eReferences name="language" eType="ecore:EClass ../MercurePL.ecore#//Language"
        lowerBound="1" containment="true" eOpposite="#//Language/mercure"/>
  </eClassifiers>
  <eSubpackages name="Factory">
    <eClassifiers xsi:type="ecore:EClass" name="FullMercure" eSuperTypes="#//Factory/MercureFactory">
      <eOperations name="make"/>
      <eOperations name="new_GUI" eType="#//GUI"/>
      <eOperations name="new_Language" eType="#//Language"/>
      <eOperations name="new_Manager" eType="#//Manager"/>
      <eOperations name="new_NetDriver" eType="#//NetDriver"/>
      <eOperations name="new_Engine" eType="#//Engine"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomMercure" eSuperTypes="#//Factory/MercureFactory">
      <eOperations name="make"/>
      <eOperations name="new_GUI" eType="#//GUI">
        <eAnnotations source="GUI1"/>
        <eAnnotations source="GUI2"/>
      </eOperations>
      <eOperations name="new_Language" eType="#//Language">
        <eAnnotations source="Language2_1"/>
      </eOperations>
      <eOperations name="new_Manager" eType="#//Manager">
        <eAnnotations source="Manager1"/>
      </eOperations>
      <eOperations name="new_NetDriver" eType="#//NetDriver">
        <eAnnotations source="NetDriver1"/>
        <eAnnotations source="NetDriver2"/>
      </eOperations>
      <eOperations name="new_Engine" eType="#//Engine">
        <eAnnotations source="Engine1"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MercureFactory">
      <eOperations name="new_Language" eType="#//Language"/>
      <eOperations name="new_Manager" eType="#//Manager"/>
      <eOperations name="new_NetDriver" eType="#//NetDriver"/>
      <eOperations name="new_Engine" eType="#//Engine"/>
      <eOperations name="make"/>
      <eOperations name="new_GUI" eType="#//GUI"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MiniMercure" eSuperTypes="#//Factory/MercureFactory">
      <eOperations name="make"/>
      <eOperations name="new_GUI" eType="#//GUI">
        <eAnnotations source="GUI1"/>
      </eOperations>
      <eOperations name="new_Language" eType="#//Language">
        <eAnnotations source="Language1_1"/>
      </eOperations>
      <eOperations name="new_Manager" eType="#//Manager">
        <eAnnotations source="Manager1"/>
      </eOperations>
      <eOperations name="new_NetDriver" eType="#//NetDriver">
        <eAnnotations source="NetDriver1"/>
      </eOperations>
      <eOperations name="new_Engine" eType="#//Engine">
        <eAnnotations source="Engine1"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
